version: '3'
services:
  netdata:
    container_name: netdata
    image: netdata/netdata
    restart: unless-stopped
    #hostname: example.com # set to fqdn of host
    ports:
      - 19999:19999
    cap_add:
      - SYS_PTRACE
    security_opt:
      - apparmor:unconfined
    volumes:
      - /etc/passwd:/host/etc/passwd:ro
      - /etc/group:/host/etc/group:ro
      - /proc:/host/proc:ro
      - /sys:/host/sys:ro
  samba:
    container_name: samba
    restart: unless-stopped
    image: dperson/samba:rpi
    network_mode: host
    hostname: lilhomie_smb
    volumes:
      - "/media/elements:/elements"
    command: "-s \"elements;/elements;yes;no;yes;all;none;;elements\""
      #-w MYLAN
      #-s elements;/elements;yes;no;yes;all;all;none;;comment1
    environment:
      - "USERID=1001"
      - "GROUPID=1001"
      - "TZ=Europe/Copenhagen"
      - "NMBD=True"
      - "RECYCLE=False"
  openvpn-as:
    container_name: openvpn
    image: linuxserver/openvpn-as
    container_name: openvpn-as
    cap_add:
      - NET_ADMIN
    environment:
      - PUID=1001
      - PGID=1001
      - TZ=Europe/Copenhagen
      - INTERFACE=eth0
    volumes:
      - /media/elements/openvpn/:/config
    ports:
      - 943:943
      - 9443:9443
      - 1194:1194/udp
    restart: unless-stopped
