version: '3'
services:
  netdata:
    image: netdata/netdata
    #hostname: example.com # set to fqdn of host
    ports:
      - 19999:19999
    cap_add:
      - SYS_PTRACE
    security_opt:
      - apparmor:unconfined
    volumes:
      - /etc/passwd:/host/etc/passwd:ro
      - /etc/group:/host/etc/group:ro
      - /proc:/host/proc:ro
      - /sys:/host/sys:ro
  samba:
    #container_name: samba
    restart: unless-stopped
    image: dperson/samba
    network_mode: host
    hostname: lilhomie_smb
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/Copenhagen
    volumes:
      - "/media/elements:/elements"
    command: >
      -w MYLAN
      -s elements;/elements;yes;no;yes;all;all;none;;comment1
    environment:
      - "USERID=${PUID}"
      - "GROUPID=${PGID}"
      - "TZ=${TZ}"
      - "NMBD=True"
      - "RECYCLE=False"
