version: '3'
services:
  netdata:
    container_name: netdata
    image: netdata/netdata
    restart: unless-stopped
    #hostname: example.com # set to fqdn of host
    ports:
      - 19999:19999
    cap_add:
      - SYS_PTRACE
    security_opt:
      - apparmor:unconfined
    volumes:
      - /etc/passwd:/host/etc/passwd:ro
      - /etc/group:/host/etc/group:ro
      - /proc:/host/proc:ro
      - /sys:/host/sys:ro
  samba:
    container_name: samba
    restart: unless-stopped
    image: dperson/samba:rpi
    network_mode: host
    hostname: lilhomie_smb
    volumes:
      - "/media/elements:/elements"
    command: "-s \"elements;/elements;yes;no;yes;all;none;;elements\""
    environment:
      - "USERID=1001"
      - "GROUPID=1001"
      - "TZ=Europe/Copenhagen"
      - "NMBD=True"
      - "RECYCLE=False"
  openvpn:
    cap_add:
     - NET_ADMIN
    image: giggio/openvpn-arm
    ports:
     - "1194:1194/udp"
    restart: always
    volumes:
     - ./openvpn/conf:/etc/openvpn
